dist: bionic
language: c
compiler: gcc
before_script:
  - sudo apt-get install -y postgresql-10 postgresql-client-10 postgresql-contrib-10 postgresql-server-dev-10 libpq-dev
script: cmake . && make && make test