language: c
compiler: gcc
before_script:
  - sudo apt-get install -y postgresql-9.6 postgresql-client-9.6 postgresql-contrib-9.6 postgresql-server-dev-9.6 libpq-dev
script: cmake . && make && make test