dist: bionic
language: c
compiler: gcc
before_script:
  - cp CMakeLists.txt.travis CMakeLists.txt
script: cmake . && make && make test
addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4