# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/danmunro/github/csaw

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/danmunro/github/csaw

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danmunro/github/csaw/CMakeFiles /Users/danmunro/github/csaw/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danmunro/github/csaw/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_room

# Build rule for target.
test_room: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_room
.PHONY : test_room

# fast build rule for target.
test_room/fast:
	$(MAKE) -f CMakeFiles/test_room.dir/build.make CMakeFiles/test_room.dir/build
.PHONY : test_room/fast

#=============================================================================
# Target rules for targets named test_actions

# Build rule for target.
test_actions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_actions
.PHONY : test_actions

# fast build rule for target.
test_actions/fast:
	$(MAKE) -f CMakeFiles/test_actions.dir/build.make CMakeFiles/test_actions.dir/build
.PHONY : test_actions/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

#=============================================================================
# Target rules for targets named test_game_service

# Build rule for target.
test_game_service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_game_service
.PHONY : test_game_service

# fast build rule for target.
test_game_service/fast:
	$(MAKE) -f CMakeFiles/test_game_service.dir/build.make CMakeFiles/test_game_service.dir/build
.PHONY : test_game_service/fast

#=============================================================================
# Target rules for targets named test_client

# Build rule for target.
test_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_client
.PHONY : test_client

# fast build rule for target.
test_client/fast:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/build
.PHONY : test_client/fast

#=============================================================================
# Target rules for targets named csaw

# Build rule for target.
csaw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csaw
.PHONY : csaw

# fast build rule for target.
csaw/fast:
	$(MAKE) -f CMakeFiles/csaw.dir/build.make CMakeFiles/csaw.dir/build
.PHONY : csaw/fast

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/csaw.dir/build.make CMakeFiles/csaw.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/csaw.dir/build.make CMakeFiles/csaw.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/csaw.dir/build.make CMakeFiles/csaw.dir/src/main.c.s
.PHONY : src/main.c.s

tests/test_actions_main.o: tests/test_actions_main.c.o

.PHONY : tests/test_actions_main.o

# target to build an object file
tests/test_actions_main.c.o:
	$(MAKE) -f CMakeFiles/test_actions.dir/build.make CMakeFiles/test_actions.dir/tests/test_actions_main.c.o
.PHONY : tests/test_actions_main.c.o

tests/test_actions_main.i: tests/test_actions_main.c.i

.PHONY : tests/test_actions_main.i

# target to preprocess a source file
tests/test_actions_main.c.i:
	$(MAKE) -f CMakeFiles/test_actions.dir/build.make CMakeFiles/test_actions.dir/tests/test_actions_main.c.i
.PHONY : tests/test_actions_main.c.i

tests/test_actions_main.s: tests/test_actions_main.c.s

.PHONY : tests/test_actions_main.s

# target to generate assembly for a file
tests/test_actions_main.c.s:
	$(MAKE) -f CMakeFiles/test_actions.dir/build.make CMakeFiles/test_actions.dir/tests/test_actions_main.c.s
.PHONY : tests/test_actions_main.c.s

tests/test_client_main.o: tests/test_client_main.c.o

.PHONY : tests/test_client_main.o

# target to build an object file
tests/test_client_main.c.o:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/tests/test_client_main.c.o
.PHONY : tests/test_client_main.c.o

tests/test_client_main.i: tests/test_client_main.c.i

.PHONY : tests/test_client_main.i

# target to preprocess a source file
tests/test_client_main.c.i:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/tests/test_client_main.c.i
.PHONY : tests/test_client_main.c.i

tests/test_client_main.s: tests/test_client_main.c.s

.PHONY : tests/test_client_main.s

# target to generate assembly for a file
tests/test_client_main.c.s:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/tests/test_client_main.c.s
.PHONY : tests/test_client_main.c.s

tests/test_game_service_main.o: tests/test_game_service_main.c.o

.PHONY : tests/test_game_service_main.o

# target to build an object file
tests/test_game_service_main.c.o:
	$(MAKE) -f CMakeFiles/test_game_service.dir/build.make CMakeFiles/test_game_service.dir/tests/test_game_service_main.c.o
.PHONY : tests/test_game_service_main.c.o

tests/test_game_service_main.i: tests/test_game_service_main.c.i

.PHONY : tests/test_game_service_main.i

# target to preprocess a source file
tests/test_game_service_main.c.i:
	$(MAKE) -f CMakeFiles/test_game_service.dir/build.make CMakeFiles/test_game_service.dir/tests/test_game_service_main.c.i
.PHONY : tests/test_game_service_main.c.i

tests/test_game_service_main.s: tests/test_game_service_main.c.s

.PHONY : tests/test_game_service_main.s

# target to generate assembly for a file
tests/test_game_service_main.c.s:
	$(MAKE) -f CMakeFiles/test_game_service.dir/build.make CMakeFiles/test_game_service.dir/tests/test_game_service_main.c.s
.PHONY : tests/test_game_service_main.c.s

tests/test_room_main.o: tests/test_room_main.c.o

.PHONY : tests/test_room_main.o

# target to build an object file
tests/test_room_main.c.o:
	$(MAKE) -f CMakeFiles/test_room.dir/build.make CMakeFiles/test_room.dir/tests/test_room_main.c.o
.PHONY : tests/test_room_main.c.o

tests/test_room_main.i: tests/test_room_main.c.i

.PHONY : tests/test_room_main.i

# target to preprocess a source file
tests/test_room_main.c.i:
	$(MAKE) -f CMakeFiles/test_room.dir/build.make CMakeFiles/test_room.dir/tests/test_room_main.c.i
.PHONY : tests/test_room_main.c.i

tests/test_room_main.s: tests/test_room_main.c.s

.PHONY : tests/test_room_main.s

# target to generate assembly for a file
tests/test_room_main.c.s:
	$(MAKE) -f CMakeFiles/test_room.dir/build.make CMakeFiles/test_room.dir/tests/test_room_main.c.s
.PHONY : tests/test_room_main.c.s

tests/test_socket_main.o: tests/test_socket_main.c.o

.PHONY : tests/test_socket_main.o

# target to build an object file
tests/test_socket_main.c.o:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket_main.c.o
.PHONY : tests/test_socket_main.c.o

tests/test_socket_main.i: tests/test_socket_main.c.i

.PHONY : tests/test_socket_main.i

# target to preprocess a source file
tests/test_socket_main.c.i:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket_main.c.i
.PHONY : tests/test_socket_main.c.i

tests/test_socket_main.s: tests/test_socket_main.c.s

.PHONY : tests/test_socket_main.s

# target to generate assembly for a file
tests/test_socket_main.c.s:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket_main.c.s
.PHONY : tests/test_socket_main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test_room"
	@echo "... test_actions"
	@echo "... test"
	@echo "... test_socket"
	@echo "... test_game_service"
	@echo "... edit_cache"
	@echo "... test_client"
	@echo "... csaw"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/test_actions_main.o"
	@echo "... tests/test_actions_main.i"
	@echo "... tests/test_actions_main.s"
	@echo "... tests/test_client_main.o"
	@echo "... tests/test_client_main.i"
	@echo "... tests/test_client_main.s"
	@echo "... tests/test_game_service_main.o"
	@echo "... tests/test_game_service_main.i"
	@echo "... tests/test_game_service_main.s"
	@echo "... tests/test_room_main.o"
	@echo "... tests/test_room_main.i"
	@echo "... tests/test_room_main.s"
	@echo "... tests/test_socket_main.o"
	@echo "... tests/test_socket_main.i"
	@echo "... tests/test_socket_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

