#include "word.c"
#include "action.c"

#include "actions/say_action.c"
#include "actions/move/move_action.c"
#include "actions/move/south_action.c"
#include "actions/move/north_action.c"
#include "actions/move/east_action.c"
#include "actions/move/west_action.c"
#include "actions/move/up_action.c"
#include "actions/move/down_action.c"
#include "actions/look_action.c"
#include "actions/look_at_mob_action.c"
#include "actions/repeat_action.c"

#include "action_table.c"
