#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <errno.h>
#include <arpa/inet.h>
#include "mock_client.c"
#include "client.c"
#include "mock_socket.c"
#include "socket.c"
