#include "action/event_consumer/input_to_action_event_consumer.c"
#include "socket/event_consumer/echo_event_consumer.c"
#include "socket/event_consumer/dummy_login_event_consumer.c"
#include "game/event_consumer/pulse_to_tick_event_consumer.c"
#include "game/event_consumer/increment_ticks_event_consumer.c"
#include "game/event_consumer/reset_mobs_event_consumer.c"