#include <stdio.h>
#include <stdlib.h>
#include <libpq-fe.h>
#include <uuid/uuid.h>
#include "uuid.c"
#include "db/db.h"
#include "mob/mob.h"
#include "socket/socket.h"
#include "event/event.h"
#include "game_service.c"
#include "socket/event_consumer/echo_event_consumer.c"
